/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservedRouteImport } from './routes/reserved'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUserIdIndexRouteImport } from './routes/user.$userId.index'
import { Route as UserUserIdWishlistsWishlistIdIndexRouteImport } from './routes/user.$userId.wishlists.$wishlistId.index'
import { Route as UserUserIdWishlistsWishlistIdItemIdRouteImport } from './routes/user.$userId.wishlists.$wishlistId.$itemId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservedRoute = ReservedRouteImport.update({
  id: '/reserved',
  path: '/reserved',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdIndexRoute = UserUserIdIndexRouteImport.update({
  id: '/user/$userId/',
  path: '/user/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdWishlistsWishlistIdIndexRoute =
  UserUserIdWishlistsWishlistIdIndexRouteImport.update({
    id: '/user/$userId/wishlists/$wishlistId/',
    path: '/user/$userId/wishlists/$wishlistId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserUserIdWishlistsWishlistIdItemIdRoute =
  UserUserIdWishlistsWishlistIdItemIdRouteImport.update({
    id: '/user/$userId/wishlists/$wishlistId/$itemId',
    path: '/user/$userId/wishlists/$wishlistId/$itemId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reserved': typeof ReservedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/user/$userId/': typeof UserUserIdIndexRoute
  '/user/$userId/wishlists/$wishlistId/$itemId': typeof UserUserIdWishlistsWishlistIdItemIdRoute
  '/user/$userId/wishlists/$wishlistId/': typeof UserUserIdWishlistsWishlistIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reserved': typeof ReservedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/user/$userId': typeof UserUserIdIndexRoute
  '/user/$userId/wishlists/$wishlistId/$itemId': typeof UserUserIdWishlistsWishlistIdItemIdRoute
  '/user/$userId/wishlists/$wishlistId': typeof UserUserIdWishlistsWishlistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reserved': typeof ReservedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/user/$userId/': typeof UserUserIdIndexRoute
  '/user/$userId/wishlists/$wishlistId/$itemId': typeof UserUserIdWishlistsWishlistIdItemIdRoute
  '/user/$userId/wishlists/$wishlistId/': typeof UserUserIdWishlistsWishlistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reserved'
    | '/reset-password'
    | '/verify-email'
    | '/user/$userId/'
    | '/user/$userId/wishlists/$wishlistId/$itemId'
    | '/user/$userId/wishlists/$wishlistId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reserved'
    | '/reset-password'
    | '/verify-email'
    | '/user/$userId'
    | '/user/$userId/wishlists/$wishlistId/$itemId'
    | '/user/$userId/wishlists/$wishlistId'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reserved'
    | '/reset-password'
    | '/verify-email'
    | '/user/$userId/'
    | '/user/$userId/wishlists/$wishlistId/$itemId'
    | '/user/$userId/wishlists/$wishlistId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReservedRoute: typeof ReservedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  UserUserIdIndexRoute: typeof UserUserIdIndexRoute
  UserUserIdWishlistsWishlistIdItemIdRoute: typeof UserUserIdWishlistsWishlistIdItemIdRoute
  UserUserIdWishlistsWishlistIdIndexRoute: typeof UserUserIdWishlistsWishlistIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserved': {
      id: '/reserved'
      path: '/reserved'
      fullPath: '/reserved'
      preLoaderRoute: typeof ReservedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId/': {
      id: '/user/$userId/'
      path: '/user/$userId'
      fullPath: '/user/$userId/'
      preLoaderRoute: typeof UserUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId/wishlists/$wishlistId/': {
      id: '/user/$userId/wishlists/$wishlistId/'
      path: '/user/$userId/wishlists/$wishlistId'
      fullPath: '/user/$userId/wishlists/$wishlistId/'
      preLoaderRoute: typeof UserUserIdWishlistsWishlistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId/wishlists/$wishlistId/$itemId': {
      id: '/user/$userId/wishlists/$wishlistId/$itemId'
      path: '/user/$userId/wishlists/$wishlistId/$itemId'
      fullPath: '/user/$userId/wishlists/$wishlistId/$itemId'
      preLoaderRoute: typeof UserUserIdWishlistsWishlistIdItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReservedRoute: ReservedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  UserUserIdIndexRoute: UserUserIdIndexRoute,
  UserUserIdWishlistsWishlistIdItemIdRoute:
    UserUserIdWishlistsWishlistIdItemIdRoute,
  UserUserIdWishlistsWishlistIdIndexRoute:
    UserUserIdWishlistsWishlistIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
